function [SampXYZ] = ModelCoordinates(intx, inty, intz,...
    Length_X, Length_Y, Length_Z)

intx_inty_intz=[intx' inty' intz'];
x0=0; y0=0; z0=0;

SampXYZ=[x0 y0 z0;...
     x0 y0 z0+Length_Z;...
     x0 y0+Length_Y z0;...
     x0 y0+Length_Y z0+Length_Z;...
     x0+Length_X y0 z0;...
     x0+Length_X y0 z0+Length_Z;...
     x0+Length_X y0+Length_Y z0;...
     x0+Length_X y0+Length_Y z0+Length_Z];

return
